# Site settings

title: Casey O'Brien
email: your-email@domain.com
description: "My personal site"
baseurl: ""
url: "http://caseylobrien.com" 
twitter_username: caseyobrien2014
github_username:  caseylobrien

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
